# Document and Verify

Once the requirements of the certification are identified, and the IS is mapped,
then, the next and most important step is to document the status of the IS. 

## Documentation
The most prominant form of attestation regarding the technologies used and their
implementation is a definitive document. Typically called the System Security
Play (SSP), the documentation of an IS must detail every aspect within the scope
of the certification. One concept used to limit the scope of documentation when attempting
the FedRAMP certification is the Authorization Boundary. 

By articulating an Authorization Boundary, the scope of the required documentation becomes
finite and specific. This is particularly important when documenting a SaaS that
utilizes either an enterprise or commercial Platform as a Service (PaaS). PaaS
providers such as Amazon Web Services (AWS) or Microsoft Azure are common but by
no means make up the entire field of PaaS offerings. However, they offer
tremendously helpful, readily available documentation regarding what NIST 800-53
based security products, policies, and procedures they provide for their
customers. 

Once the boundary is identified, all IS attributes that exist inside that
boundary must be documented. For example, the FedRAMP SSP is broken down into 13
documents that cover the majority of system attributes within a boundary. 

1. System Security Plan (SSP)
2. SSP ATTACHMENT 2 - User Guide 
3. SSP ATTACHMENT 3 - Digital Identity Worksheet
4. SSP ATTACHMENT 4 - Privacy Threshold Analysis (PTA)
5. SSP ATTACHMENT 4 - Privacy Impact Assessment (PIA)
6. SSP ATTACHMENT 5 - Rules of Behavior (RoB)
7. SSP ATTACHMENT 6 - Information System Contingency Plan (ISCP)
8. SSP ATTACHMENT 7 - Configuration Management Plan (CMP)
9. SSP ATTACHMENT 8 - Incident Response Plan (IRP)
10. SSP ATTACHMENT 9 - Control Implementation Summary (CIS) Workbook
11. SSP ATTACHMENT 10 - Federal Information Processing Standard (FIPS) 199
12. SSP ATTACHMENT 11 - Separation of Duties Matrix 
13. SSP ATTACHMENT 12 - Laws and Regulations
14. SSP ATTACHMENT 13 - Integrated Inventory Workbook

By using this model of separate specific documents that pertain to an area of the
IS, FedRAMP has provided a manageable framework. Specifically each area of the IS
and the pertinent documentation can be updated and revised commensurate with the
need of the component itself. Thus, when the company reorganizes, the IRP can be
updated without changing the Rules of Behavior. Thusly, when new legislation is
introduced requiring adherence, the Laws and Regulations document can guide the
requisite changes in the SSP. 


## Verify
By endeavouring to document an IS with %100 coverage, it becomes pivotal that the
documentation be reviewed and verified by more than one party. Thus, one method
utilized by successful entities is to create and maintain an internal team who's
mandate is to verify the veracity of any documentation used as part of the SSP. 
